name: Minimal Output Demo

on: push

jobs:
  demo:
    runs-on: ubuntu-latest
    outputs:
      foo: ${{ steps.set-output.outputs.foo }}
    steps:
      - name: Set output
        id: set-output
        run: echo "foo=hello" >> $GITHUB_OUTPUT



