name: Run Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:       # Allows manual trigger

jobs:
  scheduled-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print scheduled message
        run: |
          echo "⏰ This workflow runs every 5 minutes."
          date

